### ISSUE TITLE
nix-installer v0.10.0 fails when installing Nix 2.15.0 in Debian 12.0 container in Proxmox 8.0.3.

### ISSUE THREAD

**Issue by derekmahar** [DeterminateSystems/nix-installer#540] opened 2023-06-28 14:27 UTC
`nix-installer` v0.10.0 fails when installing Nix 2.15.0 in Debian 12.0 container in Proxmox 8.0.3.

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
```

## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `setup_default_profile` errored
   4: Failed to execute command with status 1 `HOME="/root" NIX_SSL_CERT_FILE="/nix/store/ba4f8msp39cfvfpw3m7fsalb4psw347z-nss-cacert-3.83/etc/ssl/certs/ca-bundle.crt" "/nix/store/556bgbl9z8jm7030g1b31d0cblf09036-nix-2.15.0/bin/nix-env" "-i" "/nix/store/556bgbl9z8jm7030g1b31d0cblf09036-nix-2.15.0"`, stdout: 
      stderr: installing 'nix-2.15.0'
      [31;1merror:[0m setting uid: [35;1mInvalid argument[0m
      error: cannot kill processes for uid '872415232': failed with exit code 1


```

## Metadata
|key|value|
|--|--|
|**version**|0.10.0|
|**os**|linux|
|**arch**|x86_64|

```
$ uname -a
Linux debian-1 6.2.16-3-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.16-3 (2023-06-17T05:58Z) x86_64 GNU/Linux
```

**Comment by Hoverbear** [comment] 2023-06-28 14:52
Duplicate of https://github.com/DeterminateSystems/nix-installer/issues/539

**Closed by Hoverbear** 2023-06-28 14:52 UTC
