### ISSUE TITLE
Support resumption of partially successful installations and repair of broken installations by making every `Action` idempotent and comparing the actual state of the system to that in the plan or receipt

### ISSUE THREAD

**Issue by daniel-levin** [DeterminateSystems/nix-installer#209] opened 2023-01-25 06:59 UTC
Hi there! I'm a Nix newbie who is very excited about this project. So far, I love it and I'm sold. 

I've got some ideas that I want to share because I think they have merit. I understand that this project is experimental, and that what I'm suggesting is quite a large change. I'd like to solicit feedback from the maintainers to see if what I'm saying has value.

I want Nix installs to be automatically resumable and repairable. This means that if something goes wrong during an installation, or something gets broken after an installation, the installer can restore the system to a good state. This is not an easy thing to do. I don't think it'll be easy to retrofit either. With that said, it is possible to start supporting automatic resumption and repair, provided certain constraints on actions are made.

Currently, `Action`s are designed to be reversible. This is an excellent design decision. I'd like to propose two additional constraints on actions:

1. Actions must be idempotent (in other words, safely "replayable").
2. Actions must be able to compare the state of the actual installation against the state they expect.

Under these constraints, the application of a plan can be safely done under the following circumstances:

1. No Nix has been installed
2. An installation has partially succeeded
3. Something external broke the installation in some way.

In some sense, the receipt becomes a write-ahead-log and the installer re-applies the actions in there, unless it knows the action is unnecessary.

By way of example, the following happens today:
```
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
Nix was installed successfully!

# rm -rf /etc/nix

$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

Found existing plan in `/nix/receipt.json`, with the same settings, already completed, try uninstalling and reinstalling if Nix isn't working

$ /nix/nix-installer uninstall

Proceed? ([Y]es/[n]o/[e]xplain): y
 INFO Revert: Configure Nix
Error: 
   0: Error executing action
   1: Remove file `/etc/nix/nix.conf`
   2: No such file or directory (os error 2)
```

The problem is that a something (me) has made the actual state of the system diverge from that specified in the receipt. Currently, the installer doesn't detect this can can't patch it up. Additionally, the uninstaller cannot uninstall what's already there.

It would be valuable if the `nix-installer` could idempotently re-install Nix, patching over the differences between the actual and the expected state of the installation.

**Comment by Hoverbear** [comment] 2023-01-26 16:47
Hey!

Yes this is one of the things we are sorta working towards! Several actions are already idempotent and we have #35 noting some thoughts. We also would like to be able to recognize existing known-good nix installs and offer a chance to remove them (mostly) cleanly.

This state divergence is indeed an issue and one we can certainly improve on.

A good first step would be working to make all the base actions idempotent, as from there we should be able to make most of the others idempotent. Contributions towards this goal would be most welcome, otherwise we'll likely get to it ourselves in time.

**Comment by Hoverbear** [comment] 2023-01-31 17:40
I am going to close this as it is a duplicate of #35 in many ways, this is still an eventual goal!

**Closed by Hoverbear** 2023-01-31 17:40 UTC
