### ISSUE TITLE
"launchctl" "bootout" "system" "/Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist" Boot-out failed: 5: Input/output error

### ISSUE THREAD

**Issue by mubarak23** [DeterminateSystems/nix-installer#1191] opened 2024-09-22 07:40 UTC
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_nix_hook_service` errored
   3: Failed to execute command with status 5 `"launchctl" "bootout" "system" "/Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist"`, stdout: 
      stderr: Boot-out failed: 5: Input/output error


```

## Metadata
|key|value|
|--|--|
|**version**|0.26.2|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment] 2024-09-23 14:47
Does `/Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist` exist when you run into this failure? Is there anything (interesting) in `/nix/.nix-installer-hook.out.log` or `/nix/.nix-installer-hook.err.log`? What does `ps aux | grep nix-installer` show, if anything?

**Comment by jhult** [comment] 2024-09-23 18:23
Might be a dupe of #1187

**Comment by cole-h** [comment] 2024-09-24 17:27
Yep, thanks!

**Closed by cole-h** 2024-09-24 17:27 UTC
Labels: MacOS
