### ISSUE TITLE
Issue with page `src/pages/start/1.install.mdx`

### ISSUE THREAD

**Issue by JanneM** [DeterminateSystems/nix-installer#256] opened 2023-02-17 00:05 UTC
Running the nix installer on Ubuntu 22.04 created /etc/bashrc with access rights only by root, resulting in an error" bash: /etc/bashrc: Åtkomst nekas" ("access denied") on opening each new shell. 

*Please* make this thing installable without root (or chroot). That would make this far more usable. Uninstalling for now.

**Comment by Hoverbear** [comment] 2023-02-17 17:41
This is a duplicate of #254 . Sorry about the issue you faced!

**Closed** 2023-02-17 17:41 UTC
