### ISSUE TITLE
macOS: `/etc/bashrc` and `/etc/zshrc` converted from links to regular files each reboot

### ISSUE THREAD

**Issue by eripa** [DeterminateSystems/nix-installer#721] opened 2023-11-12 20:20 UTC
Hi,

I have a slightly different issue than #593, but seem related. The workaround in #593 only checks the content of the file, and not the file type. I'll try and get a PR submitted.

Instead of the below files being overwritten on upgrades, _each time_ I reboot my machine the symbolic links are dereferenced and "converted" to real files.

Before reboot (symlinks):

```shell
$ ls -l /etc/zshrc /etc/bashrc
lrwxr-xr-x 1 root wheel 18 Nov 12 12:16 /etc/bashrc -> /etc/static/bashrc
lrwxr-xr-x 1 root wheel 17 Nov 12 12:16 /etc/zshrc -> /etc/static/zshrc
```

After reboot (regular files):

```shell
$ ls -l /etc/zshrc /etc/bashrc
-rw-r--r-- 1 root wheel 1.2K Nov 12 12:11 /etc/bashrc
-rw-r--r-- 1 root wheel 1.2K Nov 12 12:11 /etc/zshrc
```

Which then results in:

```shell
error: Unexpected files in /etc, aborting activation
The following files have unrecognized content and would be overwritten:

  /etc/bashrc
  /etc/zshrc

Please check there is nothing critical in these files, rename them by adding .before-nix-darwin to the end, and then try again.
```

nix installed via using the Determinate systems installer **0.14.0**.

```
$ nix --version
nix (Nix) 2.18.1
```

macOS:
```
 System Version:	macOS 14.1.1 (23B2082)
  Kernel Version:	Darwin 23.1.0
```

Installation receipt:
[receipt.json](https://github.com/DeterminateSystems/nix-installer/files/13329051/receipt.json)

**Comment by Hoverbear** [comment] 2023-11-14 15:55
I believe this may be caused by https://github.com/DeterminateSystems/nix-installer/pull/672 . 🤔

**Comment by eripa** [comment] 2023-11-14 15:58
Thanks for the reply @Hoverbear.  Yes, I was running nix from the determinate installer installed a few months ago that didn't experience this behaviour, so something has regressed since then.

**Comment by dhess** [comment] 2023-11-14 16:54
Yes, I'm seeing this behavior as well with dac0adca283589262356bd6ab4cd7090bfa4ee00.

**Comment by Hoverbear** [comment] 2023-11-14 17:36
We're investigating, thanks for this report. We are cutting a new release soon, it may not have a fix for this specific problem, that'll have to wait for a future release.

**Comment by purplenoodlesoop** [comment] 2023-12-03 02:35
+1, experiencing this too and it makes using `nix-darwin` far less comfortable

**Comment by Hoverbear** [comment] 2023-12-04 20:16
I discussed this with @grahamc and the planned solution would be to not do the shell recovery if the files are symlinks.

**Comment by Hoverbear** [comment] 2023-12-05 19:17
This should be fixed in the next release!

**Comment by eripa** [comment] 2023-12-05 19:25
Love it, thank you!!

**Comment by purplenoodlesoop** [comment] 2023-12-08 02:17
@Hoverbear tysm!

**Comment by steinuil** [comment] 2024-01-18 11:35
I'm a bit lost on the upgrading steps.

- Running `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install` prompted me to run `/nix/nix-installer uninstall`
- Running `/nix/nix-installer uninstall` prompted me to uninstall `nix-darwin`
- I ran `nix run nix-darwin#darwin-uninstaller` (the `nix-build` method didn't work because I don't have a `nixpkgs` channel), which seemed to successfully remove `nix-darwin`

Though after that `/nix/nix-installer uninstall` again still tells me that a `nix-darwin` installation was detected.

**Comment by Hoverbear** [comment] 2024-01-18 15:26
Those should be the steps!

The installer looks for the binaries `darwin-option`, `darwin-rebuild` and runs `launchctl print system/org.nixos.activate-system`. Do any of those exist for you?

**Comment by eripa** [comment] 2024-01-19 15:45
I tried to just run the installer again, but it prompted me to uninstall or just upgrade nix. So I figured I had to uninstall/reinstall. So I did the dance, but failed with a bunch of issues related to APFS etc. Had to reboot and clean up the remnants manually (I followed the regular [nix docs](https://nixos.org/manual/nix/stable/installation/uninstall#macos)).

After that was done I rebooted and re-ran the installer and applied my flake again, it worked well. After another reboot it all seems to work fine, I don't have this issue anymore! 😄 

Thanks a lot for fixing this! 🙏 ❤️ 

It would be great to have a way to upgrade the hooks/helpers that this nix-installer puts in place w/o having to completely nuke the entire installation. 😊

**Comment by Hoverbear** [comment] 2024-01-22 19:00
@eripa I'm sorry about the apfs issues! Out of curiousity was this on Sonoma with Filevault?

**Comment by eripa** [comment] 2024-01-22 19:01
No problem @Hoverbear, I'm using macoS Sonoma with Filevault yes (fresh install, new computer)

**Comment by Hoverbear** [comment] 2024-01-22 19:02
Okay, we've seen several reports of the same situation.

**Comment by cole-h** [comment] 2024-04-15 14:27
I believe this was fixed by https://github.com/DeterminateSystems/nix-installer/pull/767 (which was released in https://github.com/DeterminateSystems/nix-installer/releases/tag/v0.16.0) -- please let me know if that is not the case!

**Closed by cole-h** 2024-04-15 14:27 UTC
Labels: bug, MacOS
