### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by joschisan** [DeterminateSystems/nix-installer#945] opened 2024-04-30 17:03 UTC
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `encrypt_apfs_volume` errored
   3: The keychain lacks a password for the already existing "Nix Store" volume on disk `disk3`, consider removing the volume with `diskutil apfs deleteVolume "Nix Store"` (if you receive error -69888, you may need to run `sudo launchctl bootout system/org.nixos.darwin-store` and `sudo launchctl bootout system/org.nixos.nix-daemon` first)
```

## Metadata
|key|value|
|--|--|
|**version**|0.18.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment] 2024-04-30 17:36
Looks like a dupe of https://github.com/DeterminateSystems/nix-installer/issues/936 -- would you mind taking a look there (especially https://github.com/DeterminateSystems/nix-installer/issues/936#issuecomment-2062718022)? Thanks!

**Closed by cole-h** 2024-04-30 17:36 UTC

**Comment by dpc** [comment] 2024-04-30 19:38
This was a setup made be a standard Nix installer, that got broken during MacOS update.

IIRC we:

* rebooted
* deleted the volume with `diskutil`(?)
* removed it from /etc/fstab and run something else that DetSys nix installer prompted us for
* DetSys installer worked then and everything is now dandy.
