### ISSUE TITLE
"launchctl" "bootout" "system" "/Library/LaunchDaemons/org.nixos.darwin-store.plist" Boot-out failed: 5: Input/output error

### ISSUE THREAD

**Issue by kharish89** [DeterminateSystems/nix-installer#1209] opened 2024-09-30 03:24 UTC
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_nix_volume` errored
   3: Action `create_volume_service` errored
   4: Failed to execute command with status 5 `"launchctl" "bootout" "system" "/Library/LaunchDaemons/org.nixos.darwin-store.plist"`, stdout: 
      stderr: Boot-out failed: 5: Input/output error


```

## Metadata
|key|value|
|--|--|
|**version**|0.26.3|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment] 2024-09-30 16:24
If you try again, does it succeed? If so, this might be a duplicate of https://github.com/DeterminateSystems/nix-installer/issues/1187 (except with a different plist).

**Closed** 2024-10-31 16:02 UTC
Labels: MacOS
