### ISSUE TITLE
broken installation on darwin

### ISSUE THREAD

**Issue by evanrichter** [DeterminateSystems/nix-installer#449] opened 2023-05-04 20:32 UTC
I'm having some issues with nix today (mainly trying to weed out the possibility that my new nix-darwin + home-manager flake is still using previous configuration from standalone home-manager usage, and prior to that nix-darwin + home-manager flakes)

So I decided to purge it as well as I could from my aarch64-darwin system. Following [this thread](https://github.com/NixOs/nix/issues/458) for all the ideas where it could have modified the disk (as well as `nix-installer uninstall`), I am fairly sure I've covered everything.

I reboot, then use the zero-to-nix copy/paste command to install nix. Everything looks good. I go to build my nix-darwin system flake:

```
% nix build .#darwinConfigurations.Evans-MacBook-Air.system
error: don't know how to recreate store derivation '/nix/store/r3axpi04zdkb116r7smnzl0hka5rks19-darwin-system-22.11.20230503.54495a4+darwin4.379d42f.drv'!
```

Never seen that error before! This same flake could build fine previous to purging nix.

Another symptom that something has gone really wrong:

```
% nix store optimise
<...snip hundreds of similar lines...>
warning: skipping suspicious writable file '/nix/store/zqcs5xahjxij0c8vfw60lnfb6d979rn2-zlib-1.2.13/lib/libz.dylib'
warning: skipping suspicious writable file '/nix/store/zqcs5xahjxij0c8vfw60lnfb6d979rn2-zlib-1.2.13/lib/libz.1.2.13.dylib'
warning: skipping suspicious writable file '/nix/store/zqcs5xahjxij0c8vfw60lnfb6d979rn2-zlib-1.2.13/lib/libz.1.dylib'
warning: skipping suspicious writable file '/nix/store/zqcs5xahjxij0c8vfw60lnfb6d979rn2-zlib-1.2.13/share/man/man3/zlib.3.gz'
```

(Repeat purging, rebooting)

Lastly I followed the official installation command on nixos.org, and the `nix store optimise` command now looks normal. However some part of the flake build is breaking on:

```
% nix --extra-experimental-features "nix-command flakes" build .#darwinConfigurations.Evans-MacBook-Air.system
error: unable to download 'https://cache.nixos.org/rafdi35p1yrhzv9n36h88pa7n69h85lv.narinfo': Problem with the SSL CA cert (path? access rights?) (77)
% curl https://cache.nixos.org/rafdi35p1yrhzv9n36h88pa7n69h85lv.narinfo                                       
404%
```

and that url is a 404 when I try with curl. I don't think that problem is related, but overall, the official nix installer seems to put my system in a better state to use nix.

**Comment by evanrichter** [comment] 2023-05-05 01:41
this reproduces on a clean mac os x vm as well:

![image](https://user-images.githubusercontent.com/330292/236362143-b1dee300-a9ca-444e-a6f4-3fbc15d1a8c1.png)

**Comment by evanrichter** [comment] 2023-05-05 03:54
I have a working nix install again so I'll post my steps for anyone else somehow in this situation:

1. Follow every step in the [MacOS uninstall directions](https://github.com/NixOS/nix/blob/master/doc/manual/src/installation/uninstall.md#macos).
2. Install a [back-dated version](https://github.com/NixOS/nix/blob/master/doc/manual/src/installation/installing-binary.md#installing-a-pinned-nix-version-from-a-url) of nix using the official installer. Nix version 2.13.0 worked for me: `sh <(curl -L https://releases.nixos.org/nix/nix-2.13.0/install)`
3. Enable flakes manually in /etc/nix/nix.conf

`nix-installer` however still doesn't work, however so this issue is still valid

**Comment by evanrichter** [comment] 2023-05-05 18:07
My host is `macOS Ventura 13.3.1 (a) (22E772610a)`. The (a) is a security patch that was just installed a couple days ago on my host, but the vm that is also affected is on version `macOS Ventura 13.3.1 (22E261)`, without the patch.

Yeah, so there must be something on my host that's still present after the official uninstall steps, that is tripping up the official current installer (nix-2.15.0). I took a guess and tried nix-2.13.0 and was able to install.

Aside: I then set `nix.package = pkgs.nix;` in my nix-darwin configuration (with `pkgs` following unstable) so I could update to nix-2.15.0, but for some reason it's not applying. `nix --version` still shows 2.13.0. I must be doing something wrong.

**Comment by Hoverbear** [comment] 2023-05-05 18:12
The good news is running `/nix/nix-installer uninstall` after "curing" over the official install scripts should clean up anything they left behind as well.

I filed #451 which should fix one of the issues you found.

I'm gonna take a bit more of a look at Nix darwin and see if I can reproduce.

**Comment by Hoverbear** [comment] 2023-05-05 18:58
On one of our ephemeral macs I tried following the flakes guide here: https://github.com/LnL7/nix-darwin#flakes-experimental

It seems to have worked ok:

```
[1] ephemeraladmin@mac-epic-turducken> ./result/sw/bin/darwin-rebuild switch --flake .#Johns-MacBook                                                                                                                                                                                                                                                         ~/bbb
warning: unknown setting 'bash-prompt-prefix'
building the system configuration...
warning: unknown setting 'bash-prompt-prefix'
warning: unknown setting 'bash-prompt-prefix'
user defaults...
setting up user launchd services...
setting up /Applications/Nix Apps...
setting up pam...
applying patches...
setting up /etc...
error: not linking environment.etc."nix/nix.conf" because /etc/nix/nix.conf already exists, skipping...
existing file has unknown content 3edebde1a77325af444bb037b0010feae345a9c426e0bb33135b73bafe605375, move and activate again to apply
system defaults...
setting up launchd services...
reloading service org.nixos.activate-system
reloading service org.nixos.nix-daemon
reloading nix-daemon...
waiting for nix-daemon
waiting for nix-daemon
configuring networking...
```

It may be what you suspect: Something left over. Hmm...

**Comment by evanrichter** [comment] 2023-05-05 22:19
another very confusing data point on the nixos.org installer: on a brand new `aarch64-darwin` host (not vm) the current nixos.org installer (v2.15.0) works perfectly :|

**Comment by Hoverbear** [comment] 2023-05-08 16:12
That's good news at least! :)

**Comment by takeda** [comment] 2023-05-15 18:28
@Hoverbear was the fix already released? I installed nix last Saturday and still got this issue. Also is there any way to get it resolved without going through the process of uninstalling and installing again?

**Comment by Hoverbear** [comment] 2023-05-16 15:33
@takeda there are a few issues mentioned in this thread and I can't be sure which one you are referring to. So I'll list them:

> `% nix build .#darwinConfigurations.Evans-MacBook-Air.system` not working

I haven't been able to reproduce this and am not sure what's happening here. In https://github.com/DeterminateSystems/nix-installer/issues/449#issuecomment-1536651647 I played around and it seemed to work out okay.

> `% nix store optimise` throwing warnings

https://github.com/DeterminateSystems/nix-installer/pull/451 fixes this but hasn't been released.

> ```
> % nix --extra-experimental-features "nix-command flakes" build .#darwinConfigurations.Evans-MacBook-Air.system
> error: unable to download 'https://cache.nixos.org/rafdi35p1yrhzv9n36h88pa7n69h85lv.narinfo': Problem with the SSL CA cert (path? access rights?) (77)
> % curl https://cache.nixos.org/rafdi35p1yrhzv9n36h88pa7n69h85lv.narinfo                                       
> 404%
> ```

I am not sure this was a bug or an ephemeral issue the user experienced. (I'd like to know if it was actually a bug)

We haven't cut a release in a couple weeks, but likely will quite soon as we've updated our planners to use 2.15 and some new features.

If the issue is fixed, then it's likely to require an uninstall and reinstall. :(

**Comment by evanrichter** [comment] 2023-05-16 16:55
oh shoot somehow I read your previous comment out of order or something.

when #451 ships, I can re-test my flake build. Or earlier, if there's a binary of `nix-installer` available with #451

**Comment by takeda** [comment] 2023-05-17 05:44
@Hoverbear yes, I was referring to the issue addressed in https://github.com/DeterminateSystems/nix-installer/pull/451, thanks.

I ended up reinstalling with the original nix installer as some changes made here (primarily removing channels) seem to not play too well with nix-darwin.

**Comment by takeda** [comment] 2023-05-17 17:15
BTW: there's an issue on OS X: https://github.com/NixOS/nix/issues/7273 this is unrelated to this installer since it also happens when nix is installed with the official installer and `auto-optimise-store = true` is enabled. I'm wondering if this should be kept enabled on OS X.

**Comment by blakesweeney** [comment] 2023-07-04 08:14
I found this issue trying to solve the `Problem with the SSL CA cert (path? access rights?) (77)` issue and found that the way to solve that was to use nix-installer to uninstall and then remove files in `/etc` that were symlinks to `/etc/static`. It seems that the offical nix installer would put symlinks from `/etc` to `/etc/static` and these links get broken on uninstall. I'm guessing the `ca-certificates.crt` file that was broken was the cause of the message. Neither the offical instructions or `nix-installer` remove the links. Removing those symlinks by hand and then reinstalling with `nix-installer` seems to fix the issue.

**Comment by Hoverbear** [comment] 2023-07-04 14:55
Thanks for digging into this more! Maybe we can teach `nix-installer` to fix this...

**Comment by Hoverbear** [comment] 2023-07-14 19:53
In https://github.com/DeterminateSystems/nix-installer/issues/528  we noticed if you remove nix without removing nix-darwin first, you can encounter some quite strange errors which look similar to these. We have partially mitigated this by warning you if we detect `nix-darwin` on your system before uninstalling, however it's only a partial fix/mitigation.  https://github.com/DeterminateSystems/nix-installer/pull/561

**Comment by Hoverbear** [comment] 2023-09-08 19:00
I think the issues found here are resolved, if they're not, feel free to reopen!

**Closed by Hoverbear** 2023-09-08 19:00 UTC
Labels: bug, MacOS, Has workaround
