### ISSUE TITLE
Draft: Unable to Uninstall Nix 

### ISSUE THREAD

**Issue by ar4s-gh** [DeterminateSystems/nix-installer#971] opened 2024-05-23 01:42 UTC
Forgive me for dumping this here for now, I haven't yet had time to review the contributing guidelines but would like to have this looked into.

notes 

Mac mini (m1), Sonoma 14.5

```
shroot@shroots-Mac-mini ~ % nix --version
nix (Nix) 2.21.2
shroot@shroots-Mac-mini ~ % /nix/nix-installer uninstall
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Password:
Sorry, try again.
Password:
Nix uninstall plan (v0.19.0)

Planner: macos

Configured settings:
* root_disk: "disk3"

Planned actions:
* Unconfigure Nix daemon related settings with launchctl
* Delete file `/Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist`
* Remove the Nix configuration from zsh's non-login shells
* Unconfigure the shell profiles
* Remove the Nix configuration in `/etc/nix/nix.conf`
* Unset the default Nix profile
* Remove time machine exclusions
* Remove Nix users and group
* Remove the directory tree in `/nix`
* Remove the APFS volume `Nix Store` on `disk3`


Proceed? ([Y]es/[n]o/[e]xplain): Y
 INFO Revert: Remove directory `/nix/temp-install-dir`
 INFO Revert: Configure Nix daemon related settings with launchctl
 INFO Revert: Create a `launchctl` plist to put Nix into your PATH
 INFO Revert: Configuring zsh to support using Nix in non-interactive shells
 INFO Revert: Configure Nix
 INFO Revert: Configure Time Machine exclusions
 INFO Revert: Create build users (UID 301-332) and group (GID 30000)
 INFO Revert: Provision Nix
 INFO Revert: Create an APFS volume `Nix Store` for Nix on `disk3` and add it to `/etc/fstab` mounting on `/nix`
ERROR Uninstallation complete, some errors encountered
Error: 
   0: Error reverting
   0: Action `create_apfs_volume` errored
      Failed to execute command with status 1 `"/usr/sbin/diskutil" "apfs" "deleteVolume" "Nix Store"`, stdout: Started APFS operation
      Deleting APFS Volume from its APFS Container
      Unmounting disk4s7
      The volume "Nix Store" on disk4s7 couldn't be unmounted because it is in use by process 0 (kernel)

      stderr: Error: -69888: Couldn't unmount disk


   0: 

Location:
   src/cli/subcommand/uninstall.rs:192

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Consider reporting this error using this URL: https://github.com/DeterminateSystems/nix-installer/issues/new?title=%3Cautogenerated-issue%3E&body=%23%23+Error%0A%60%60%60%0AError%3A+%0A+++0%3A+Error+reverting%0A+++0%3A+Action+%60create_apfs_volume%60+errored%0A++++++Failed+to+execute+command+with+status+1+%60%22%2Fusr%2Fsbin%2Fdiskutil%22+%22apfs%22+%22deleteVolume%22+%22Nix+Store%22%60%2C+stdout%3A+Started+APFS+operation%0A++++++Deleting+APFS+Volume+from+its+APFS+Container%0A++++++Unmounting+disk4s7%0A++++++The+volume+%22Nix+Store%22+on+disk4s7+couldn%27t+be+unmounted+because+it+is+in+use+by+process+0+%28kernel%29%0A%0A++++++stderr%3A+Error%3A+-69888%3A+Couldn%27t+unmount+disk%0A%0A%0A%0A%60%60%60%0A%0A%23%23+Metadata%0A%7Ckey%7Cvalue%7C%0A%7C--%7C--%7C%0A%7C**version**%7C0.19.0%7C%0A%7C**os**%7Cmacos%7C%0A%7C**arch**%7Caarch64%7C%0A
shroot@shroots-Mac-mini ~ % 

```

**Comment by cole-h** [comment] 2024-06-03 20:06
This looks like a duplicate of https://github.com/DeterminateSystems/nix-installer/issues/764. If you reboot, is the volume still there? If so, you should be able to delete it safely (because this is the final step of the uninstaller, it should be safe to delete -- once macOS deigns to let you do so).

**Closed by cole-h** 2024-06-03 20:06 UTC
Labels: duplicate, MacOS
