### ISSUE TITLE
Cannot set UID, invalid argument

### ISSUE THREAD

**Issue by veryniceworld** [DeterminateSystems/nix-installer#613] opened 2023-08-25 05:52 UTC
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `setup_default_profile` errored
   4: Failed to execute command with status 1 `HOME="/root" NIX_SSL_CERT_FILE="/nix/store/ba4f8msp39cfvfpw3m7fsalb4psw347z-nss-cacert-3.83/etc/ssl/certs/ca-bundle.crt" "/nix/store/3wqasl97rjiza3vd7fxjnvli2w9l30mk-nix-2.17.0/bin/nix-env" "-i" "/nix/store/3wqasl97rjiza3vd7fxjnvli2w9l30mk-nix-2.17.0"`, stdout: 
      stderr: installing 'nix-2.17.0'
      [31;1merror:[0m setting uid: [35;1mInvalid argument[0m
      error: cannot kill processes for uid '872415232': failed with exit code 1


```

## Metadata
|key|value|
|--|--|
|**version**|0.11.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by Hoverbear** [comment] 2023-08-31 16:21
It looks like your system doesn't support dynamic users, could you tell me which distribution this is?

**Comment by grahamc** [comment] 2023-09-22 14:51
I think this is a duplicate of #539.

**Comment by Hoverbear** [comment] 2023-09-22 15:57
Think so too, gonna close this.

**Closed by Hoverbear** 2023-09-22 15:57 UTC
Labels: question
