### ISSUE TITLE
Include shell completions

### ISSUE THREAD

**Issue by kolloch** [DeterminateSystems/nix-installer#702] opened 2023-11-02 09:06 UTC
Out-of-the box, after using `nix-installer`, the shell completions for the nix commands do not seem to be available for me. It would be nice if this included the nix commands itself but also any other commands installed by the user through nix.

[I am using the nix-installer but then override the installed nix from a flake, so I hope I didn't mess this up through that step but I don't think so.]

(Tested on Ubuntu, WSL2/Ubuntu, Mac OS)

It seems to work for me on Ubuntu [with XDG_DATA_DIRS and fpath extensions](https://gitlab.com/nexxiot-labs/nix-bootstrap/-/blob/main/src/install.sh#L96-126).

**Comment by Hoverbear** [comment] 2023-11-02 17:56
Thanks for this report: I fully agree and want this as well.

This issue is a duplicate of https://github.com/DeterminateSystems/nix-installer/issues/486, for which a fix has been proposed upstream (https://github.com/NixOS/nix/pull/8985). Progress there seems to have stalled so perhaps we need to consider adding this to the installer instead -- it's just a pain.

**Closed by Hoverbear** 2023-11-02 17:56 UTC
