### ISSUE TITLE
Failed to install - selinux problem

### ISSUE THREAD

**Issue by viperML** [DeterminateSystems/nix-installer#611] opened 2023-08-22 20:49 UTC
I've been using nixos for more than a year, and decided to try nix on Silverblue. I get the following rust trace:

## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_init_service` errored
   3: Failed to execute command with status 1 `"systemctl" "enable" "/nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.socket" "--now"`, stdout: 
      stderr: Failed to enable unit: Access denied


```

## Metadata
|key|value|
|--|--|
|**version**|0.11.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by Hoverbear** [comment] 2023-08-31 16:17
Is there something preventing your root user from being able to enable systemd units?

**Comment by calebmaxted** [comment] 2023-09-02 11:44
Same error on Alma 8.8.
Seems to be SELinux related.  As soon as this error from nix-installer pops up, I get 5 identical AVC denials:

`type=AVC msg=audit(1693654263.383:458): avc:  denied  { read } for  pid=1 comm="systemd" name="lib" dev="vda1" ino=2278777 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:default_t:s0 tclass=lnk_file permissive=0`

**Comment by calebmaxted** [comment] 2023-09-02 19:01
`sealert -a /var/log/audit/audit.log` suggests running the following:
`ausearch -c 'systemd' --raw | audit2allow -M my-systemd` (this creates the files attached below)
`semodule -X 300 -i my-systemd.pp`

Afterwords, re-running nix-installer finishes successfully.

[my-systemd.tgz](https://github.com/DeterminateSystems/nix-installer/files/12504566/my-systemd.tgz)

**Comment by Hoverbear** [comment] 2023-09-05 15:37
Thank you! It seems we have a bug!

**Comment by Hoverbear** [comment] 2023-09-06 18:17
I've tested this on stock installs (in VMs) of Fedora Silverblue and Alma Linux without a reproduction. Could you help me better understand the differences that might exist between your system and mine?

**Comment by calebmaxted** [comment] 2023-09-07 21:09
Hmm... In my case, I'm running an Alma 8 VM on a (small, relatively unknown) VPS provider.  However, I do know that this provider modifies (at least some of) their VM templates to work with their older VM platform.

I re-installed from scratch using their Alma 8 template.  They disable SELinux by default (sigh), so I have to enable it and relabel the files.  Immediately after a reboot, with no other modifications, running the nix-installer fails with the above error.

I then re-installed using their Alma 9 template.  Again I have to enable SELinux and relabel files.  But this time the nix-installer succeeds.

I feel like this is a problem with my VPS provider and their botched Alma 8 template.  I will consider this issue closed on my end, though @viperML is likely not in the same scenario as me.

Thank you, @Hoverbear, for your time and help.

**Comment by viperML** [comment] 2023-09-07 21:12
As I mentioned, I wiped my Linux install from this computer and don't plan to install again, so I don't have any strong interest in keeping this open. My installation was just stock fedora silverblue with the linux-surface kernel, which I doubt it would have any effect.

**Comment by Hoverbear** [comment] 2023-09-08 15:20
Okay, closing. Thanks!

**Closed by Hoverbear** 2023-09-08 15:20 UTC
Labels: bug, Linux
