### ISSUE TITLE
Error about missing nixbld group (after uninstalling nix)

### ISSUE THREAD

**Issue by tennox** [DeterminateSystems/nix-installer#328] opened 2023-03-12 22:54 UTC
## Error
```
Error: 
   0: Install failure
   1: Error executing action `configure_nix`
   2: Child action `setup_default_profile`
   3: Failed to execute command with status 1 `"/nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3/bin/nix-env" "-i" "/nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3"`, stdout: 
      stderr: warning: the group 'nixbld' specified in 'build-users-group' does not exist
      installing 'nix-2.13.3'
      error: the group 'nixbld' specified in 'build-users-group' does not exist


```

I just uninstalled the nix I had installed using the "normal" installation method following these steps:
https://nixos.org/manual/nix/stable/installation/installing-binary.html#uninstalling

But your installer seems to not create the group correctly?

I'm on Fedora 37

Full log
<details>
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
info: downloading installer https://install.determinate.systems/nix/tag/v0.5.0/nix-installer-x86_64-linux
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Nix install plan (v0.5.0)

Planner: linux

Planner settings:

* force: false
* nix_build_user_prefix: "nixbld"
* nix_package_url: "https://releases.nixos.org/nix/nix-2.13.3/nix-2.13.3-x86_64-linux.tar.xz"
* channels: ["nixpkgs=https://nixos.org/channels/nixpkgs-unstable"]
* nix_build_user_count: 32
* nix_build_group_id: 30000
* nix_build_user_id_base: 30000
* nix_build_group_name: "nixbld"
* diagnostic_endpoint: "https://install.determinate.systems/nix/diagnostic"
* extra_conf: []
* init: "Systemd"
* modify_profile: true
* start_daemon: true

The following actions will be taken:

* Create build users (UID 30000-30032) and group (GID 30000)
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Place channel configuration at `/root/.nix-channels`
* Configure the shell profiles
* Configure Nix daemon related settings with systemd

Proceed? ([Y]es/[n]o/[e]xplain): e
Nix install plan (v0.5.0)

Planner: linux

Planner settings:

* nix_build_user_id_base: 30000
* nix_build_user_prefix: "nixbld"
* init: "Systemd"
* nix_build_group_name: "nixbld"
* nix_package_url: "https://releases.nixos.org/nix/nix-2.13.3/nix-2.13.3-x86_64-linux.tar.xz"
* force: false
* diagnostic_endpoint: "https://install.determinate.systems/nix/diagnostic"
* nix_build_group_id: 30000
* extra_conf: []
* start_daemon: true
* nix_build_user_count: 32
* channels: ["nixpkgs=https://nixos.org/channels/nixpkgs-unstable"]
* modify_profile: true

The following actions will be taken:

* Create build users (UID 30000-30032) and group (GID 30000)
  The Nix daemon requires system users (and a group they share) which it can act as in order to build
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
  This file is read by the Nix daemon to set its configuration options at runtime.
  Create directory `/etc/nix`
  Merge or create nix.conf file `/etc/nix/nix.conf`
* Place channel configuration at `/root/.nix-channels`
* Configure the shell profiles
  Update shell profiles to import Nix
* Configure Nix daemon related settings with systemd
  Run `systemd-tempfiles --create --prefix=/nix/var/nix`
  Run `systemctl link /nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.service`
  Run `systemctl link /nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.socket`
  Run `systemctl daemon-reload`
  Run `systemctl enable --now /nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.socket`

Proceed? ([Y]es/[n]o): 
 INFO Step: Create directory `/nix`
 INFO Step: Provision Nix
 INFO Step: Configure Nix
ERROR 
   0: Install failure
   1: Error executing action `configure_nix`
   2: Child action `setup_default_profile`
   3: Failed to execute command with status 1 `"/nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3/bin/nix-env" "-i" "/nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3"`, stdout: 
      stderr: warning: the group 'nixbld' specified in 'build-users-group' does not exist
      installing 'nix-2.13.3'
      error: the group 'nixbld' specified in 'build-users-group' does not exist

   3: 

Location:
   /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/convert/mod.rs:726

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Consider reporting this error using this URL: https://github.com/DeterminateSystems/nix-installer/issues/new?title=%3Cautogenerated-issue%3E&body=%23%23+Error%0A%60%60%60%0AError%3A+%0A+++0%3A+Install+failure%0A+++1%3A+Error+executing+action+%60configure_nix%60%0A+++2%3A+Child+action+%60setup_default_profile%60%0A+++3%3A+Failed+to+execute+command+with+status+1+%60%22%2Fnix%2Fstore%2Fmc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3%2Fbin%2Fnix-env%22+%22-i%22+%22%2Fnix%2Fstore%2Fmc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3%22%60%2C+stdout%3A+%0A++++++stderr%3A+warning%3A+the+group+%27nixbld%27+specified+in+%27build-users-group%27+does+not+exist%0A++++++installing+%27nix-2.13.3%27%0A++++++error%3A+the+group+%27nixbld%27+specified+in+%27build-users-group%27+does+not+exist%0A%0A%0A%60%60%60
Installation failure, offering to revert...
Nix uninstall plan

Planner: linux

Planner settings:

* nix_build_user_id_base: 30000
* force: false
* nix_build_group_id: 30000
* nix_build_group_name: "nixbld"
* nix_build_user_count: 32
* channels: ["nixpkgs=https://nixos.org/channels/nixpkgs-unstable"]
* diagnostic_endpoint: "https://install.determinate.systems/nix/diagnostic"
* nix_package_url: "https://releases.nixos.org/nix/nix-2.13.3/nix-2.13.3-x86_64-linux.tar.xz"
* modify_profile: true
* extra_conf: []
* nix_build_user_prefix: "nixbld"
* init: "Systemd"
* start_daemon: true

The following actions will be taken (`--explain` for more context):

* Unconfigure the shell profiles
* Remove channel configuration at `/root/.nix-channels`
* Remove the Nix configuration in `/etc/nix/nix.conf`
* Unset the default Nix profile
* Remove the directory tree in `/nix`
* Remove Nix users and group

Proceed? ([Y]es/[n]o/[e]xplain): 

</details

**Comment by tennox** [comment] 2023-03-12 22:58
And the revert step also has some errors:
```
The following actions will be taken (`--explain` for more context):

* Unconfigure the shell profiles
* Remove channel configuration at `/root/.nix-channels`
* Remove the Nix configuration in `/etc/nix/nix.conf`
* Unset the default Nix profile
* Remove the directory tree in `/nix`
* Remove Nix users and group


Proceed? ([Y]es/[n]o/[e]xplain): 
 INFO Revert: Configure Nix daemon related settings with systemd
 INFO Revert: Configure Nix
 INFO Revert: Provision Nix
Error: 
   0: Error executing action `provision_nix`
   1: Child action errors: Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld4"`, stdout: 
      stderr: userdel: user 'nixbld4' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld3"`, stdout: 
      stderr: userdel: user 'nixbld3' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld16"`, stdout: 
      stderr: userdel: user 'nixbld16' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld11"`, stdout: 
      stderr: userdel: user 'nixbld11' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld5"`, stdout: 
      stderr: userdel: user 'nixbld5' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld15"`, stdout: 
      stderr: userdel: user 'nixbld15' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld2"`, stdout: 
      stderr: userdel: user 'nixbld2' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld14"`, stdout: 
      stderr: userdel: user 'nixbld14' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld10"`, stdout: 
      stderr: userdel: user 'nixbld10' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld8"`, stdout: 
      stderr: userdel: user 'nixbld8' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld13"`, stdout: 
      stderr: userdel: user 'nixbld13' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld24"`, stdout: 
      stderr: userdel: user 'nixbld24' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld7"`, stdout: 
      stderr: userdel: user 'nixbld7' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld23"`, stdout: 
      stderr: userdel: user 'nixbld23' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld1"`, stdout: 
      stderr: userdel: user 'nixbld1' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld12"`, stdout: 
      stderr: userdel: user 'nixbld12' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld0"`, stdout: 
      stderr: userdel: user 'nixbld0' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld6"`, stdout: 
      stderr: userdel: user 'nixbld6' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld9"`, stdout: 
      stderr: userdel: user 'nixbld9' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld26"`, stdout: 
      stderr: userdel: user 'nixbld26' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld25"`, stdout: 
      stderr: userdel: user 'nixbld25' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld19"`, stdout: 
      stderr: userdel: user 'nixbld19' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld21"`, stdout: 
      stderr: userdel: user 'nixbld21' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld17"`, stdout: 
      stderr: userdel: user 'nixbld17' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld22"`, stdout: 
      stderr: userdel: user 'nixbld22' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld18"`, stdout: 
      stderr: userdel: user 'nixbld18' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld28"`, stdout: 
      stderr: userdel: user 'nixbld28' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld31"`, stdout: 
      stderr: userdel: user 'nixbld31' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld27"`, stdout: 
      stderr: userdel: user 'nixbld27' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld20"`, stdout: 
      stderr: userdel: user 'nixbld20' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld29"`, stdout: 
      stderr: userdel: user 'nixbld29' does not exist

      ) & Child action `create_user` (Failed to execute command with status 6 `"userdel" "nixbld30"`, stdout: 
      stderr: userdel: user 'nixbld30' does not exist

      )

Location:
   src/cli/subcommand/install.rs:220

```

**Comment by Hoverbear** [comment] 2023-03-13 18:09
This is rather puzzling, since we check during the planning phase if the group exists:

https://github.com/DeterminateSystems/nix-installer/blob/9d939e788581eeba3361e607ac8fbc3adfe70637/src/action/base/create_group.rs#L27-L40

If not, we create it.

I wonder what situation causes the installer to not detect the group needed to be created.

**Comment by Hoverbear** [comment] 2023-03-23 16:45
It doesn't seem to reproduce in tests.

**Comment by Hoverbear** [comment] 2023-03-29 17:18
I haven't managed to reproduce this, going to close it for now.

**Closed by Hoverbear** 2023-03-29 17:18 UTC
Labels: Linux
