### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by WatweA** [DeterminateSystems/nix-installer#1106] opened 2024-08-20 19:50 UTC
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `setup_default_profile` errored
   4: Failed to execute command with status 1 `HOME="/home/root" NIX_SSL_CERT_FILE="/nix/store/9m6xbd8pcdb6c655b7lifhi5m1igi5rk-nss-cacert-3.101/etc/ssl/certs/ca-bundle.crt" "/nix/store/k18sllkc3ngm40d6k81lq6wgq4hd72ix-nix-2.24.3/bin/nix-env" "--option" "substitute" "false" "-i" "/nix/store/k18sllkc3ngm40d6k81lq6wgq4hd72ix-nix-2.24.3"`, stdout: 
      stderr: installing 'nix-2.24.3'
      error:
             … while setting up the build environment

             error: unable to load seccomp BPF program: Invalid argument


```

## Metadata
|key|value|
|--|--|
|**version**|0.21.0|
|**os**|linux|
|**arch**|aarch64|

**Comment by cole-h** [comment] 2024-08-20 21:15
This looks like a duplicate of https://github.com/DeterminateSystems/nix-installer/issues/896. Please see my comment there for some things to try.

**Closed by cole-h** 2024-08-20 21:15 UTC

**Comment by WatweA** [comment] 2024-09-04 00:46
Looks like this was attributed to a few corrupted core-utils on my system. After re-flashing the disk the issue disappeared. Unsure which of the utils were causing this though.
