### ISSUE TITLE
<autogenerated-issue> while running the uninstaller

### ISSUE THREAD

**Issue by xel** [DeterminateSystems/nix-installer#1202] opened 2024-09-27 09:30 UTC
## Error
```
Error: 
   0: Error reverting
   0: Action `create_users_and_group` errored
      Multiple child errors

      Action `create_user` errored
      Failed to execute command with status 185 `"/usr/bin/dscl" "." "-delete" "/Users/_nixbld1"`, stdout: delete: Invalid Path

      stderr: <dscl_cmd> DS Error: -14009 (eDSUnknownNodeName)



      Action `create_user` errored
      Failed to execute command with status 185 `"/usr/bin/dscl" "." "-delete" "/Users/_nixbld2"`, stdout: delete: Invalid Path

      stderr: <dscl_cmd> DS Error: -14009 (eDSUnknownNodeName)



      Action `create_user` errored
      Failed to execute command with status 185 `"/usr/bin/dscl" "." "-delete" "/Users/_nixbld3"`, stdout: delete: Invalid Path

      stderr: <dscl_cmd> DS Error: -14009 (eDSUnknownNodeName)



      Action `create_user` errored
      Failed to execute command with status 185 `"/usr/bin/dscl" "." "-delete" "/Users/_nixbld4"`, stdout: delete: Invalid Path

      stderr: <dscl_cmd> DS Error: -14009 (eDSUnknownNodeName)




```

## Metadata
|key|value|
|--|--|
|**version**|0.19.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment] 2024-09-27 14:07
Looks like a dupe of https://github.com/DeterminateSystems/nix-installer/issues/1197. See my comment there (https://github.com/DeterminateSystems/nix-installer/issues/1197#issuecomment-2377121280) for more information.

If everything else succeeded, you can consider the uninstall successful.

**Closed by cole-h** 2024-09-27 14:07 UTC
