### ISSUE TITLE
Explore Nix development environments - bashrc: Permission denied

### ISSUE THREAD

**Issue by mtlynch** [DeterminateSystems/nix-installer#262] opened 2023-02-18 02:34 UTC
Thanks for this tutorial! I'm totally new to Nix and had been curious for a while about trying it out. This tutorial is a great, gentle intro.

I ran into a small bug on Chapter 3. I get a permission denied error when I run the first example:

```bash
 nix develop "github:DeterminateSystems/zero-to-nix#example"
bash: /etc/bashrc: Permission denied
(nix:zero-to-nix-env) mike@ztn:~$ type curl
curl is /nix/store/6bcbqn79a53kh2li91vkggyzl7j3h5d7-curl-7.86.0-bin/bin/curl
```

Things seem to be working, but I'm not sure why the error is popping up. This is on a bare Debian 11 system:

```bash
$ uname -a && lsb_release -a
Linux ztn 5.10.0-21-amd64 DeterminateSystems/zero-to-nix#1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by Hoverbear** [comment] 2023-02-23 19:22
I think you might have been caught by a small permissions issue which we've now fixed. We're releasing a new version tomorrow that will include it! In the meantime I *think* the problem is your bashrc has the wrong permissions?

Could you share the output of `ls -lah /etc/bashrc`? 

Here's mine:

```
ana@ubuntu-base:~/Downloads$ ls -lah /etc/bash.bashrc 
-rw-r--r-- 1 root root 2.5K Feb 23 11:21 /etc/bash.bashrc
```

**Comment by mtlynch** [comment] 2023-02-24 16:07
I tried reproducing this on a Docker image of Debian Bullseye (`docker run -it `)

```bash
mike@6c4bb54b4eae:/$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
info: downloading installer https://install.determinate.systems/nix/tag/v0.3.0/nix-installer-x86_64-linux
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Nix install plan (v0.3.0)

Planner: linux

Planner settings:

* extra_conf: []
* nix_build_user_count: 32
* nix_build_group_name: "nixbld"
* force: false
* channels: ["nixpkgs=https://nixos.org/channels/nixpkgs-unstable"]
* nix_build_user_id_base: 30000
* nix_package_url: "https://releases.nixos.org/nix/nix-2.13.2/nix-2.13.2-x86_64-linux.tar.xz"
* nix_build_group_id: 30000
* modify_profile: true
* start_daemon: false
* nix_build_user_prefix: "nixbld"
* init: "None"

The following actions will be taken:

* Create directory `/nix`
* Fetch `https://releases.nixos.org/nix/nix-2.13.2/nix-2.13.2-x86_64-linux.tar.xz` to `/nix/temp-install-dir`
* Create build users (UID 30000-30032) and group (GID 30000)
* Create a directory tree in `/nix`
* Move the downloaded Nix into `/nix`
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Place channel configuration at `/root/.nix-channels`
* Configure the shell profiles


Proceed? ([Y]es/[n]o/[e]xplain): y
 INFO Step: Create directory `/nix`
 INFO Step: Provision Nix
 INFO Step: Configure Nix
 INFO Step: Leave the Nix daemon unconfigured
Nix was installed successfully!
To get started using Nix, open a new shell or run `. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`

mike@6c4bb54b4eae:/$ nix develop "github:DeterminateSystems/zero-to-nix#example"
error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted
```

It looks like the permissions on `/etc/bashrc` are different on Debian Bullseye than your Ubuntu install:

```bash
mike@6c4bb54b4eae:/$ ls -lah /etc/bashrc
-rw------- 1 root root 172 Feb 24 16:03 /etc/bashrc
```

**Comment by Avi-D-coder** [comment] 2023-02-28 23:18
Any workarounds for this issue?

**Comment by Hoverbear** [comment] 2023-03-02 16:09
@mtlynch unfortunately Docker doesn't support systemd, which means we need to install Nix daemonless in a root-only mode. I see your user is some non-root user, so you'd need to run `nix develop` with sudo.

Running as root should work:

```
❯ sudo docker run -it debian:bullseye-20230208-slim
root@0c2c3ec2cf2a:/# apt update -q && apt install curl -q
# ...
root@0c2c3ec2cf2a:/# curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
info: downloading installer https://install.determinate.systems/nix/tag/v0.4.0/nix-installer-x86_64-linux
Nix install plan (v0.4.0)

Planner: linux

Planner settings:

* extra_conf: []
* nix_build_group_name: "nixbld"
* force: false
* nix_package_url: "https://releases.nixos.org/nix/nix-2.13.2/nix-2.13.2-x86_64-linux.tar.xz"
* modify_profile: true
* nix_build_user_id_base: 30000
* nix_build_user_count: 32
* nix_build_user_prefix: "nixbld"
* start_daemon: false
* nix_build_group_id: 30000
* init: "None"
* channels: ["nixpkgs=https://nixos.org/channels/nixpkgs-unstable"]
* diagnostic_endpoint: "https://install.determinate.systems/nix/diagnostic"

The following actions will be taken:

* Create directory `/nix`
* Fetch `https://releases.nixos.org/nix/nix-2.13.2/nix-2.13.2-x86_64-linux.tar.xz` to `/nix/temp-install-dir`
* Create build users (UID 30000-30032) and group (GID 30000)
* Create a directory tree in `/nix`
* Move the downloaded Nix into `/nix`
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Place channel configuration at `/root/.nix-channels`
* Configure the shell profiles


Proceed? ([Y]es/[n]o/[e]xplain): y
 INFO Step: Create directory `/nix`
 INFO Step: Provision Nix
 INFO Step: Configure Nix
 INFO Step: Leave the Nix daemon unconfigured
Nix was installed successfully!
To get started using Nix, open a new shell or run `. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`

root@0c2c3ec2cf2a:/# . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
root@0c2c3ec2cf2a:/# nix run nixpkgs#hello
Hello, world!
root@0c2c3ec2cf2a:/# 
```

And as a user:

```
root@0c2c3ec2cf2a:/# su ana
$ nix run nixpkgs#hello
error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted
```

**Closed** 2023-03-02 16:09 UTC

**Comment by houqp** [comment] 2023-04-09 23:17
@Hoverbear curious what's the reason that we couldn't get non-root user to work with nix-installer? The `--no-daemon` option from the upstream installer works well with non-root user in a docker.
