### ISSUE TITLE
Steam Deck installation crashes desktop session

### ISSUE THREAD

**Issue by lluchs** [DeterminateSystems/nix-installer#145] opened 2022-12-28 15:39 UTC
I tried the installer on my Steam Deck after reading your blog post. Thanks for your work, Nix may be a more convenient way of installing additional software on SteamOS.

The installer worked fine, but somehow crashed my desktop session. Here's some logs, maybe you can figure out what happened:

Installer output (looks as expected):
```
deck@steamdeck /sys curl -L https://install.determinate.systems/nix | sh -s -- install steam-deck                                                                    
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 15714  100 15714    0     0   5589      0  0:00:02  0:00:02 --:--:-- 48055
info: downloading installer (https://install.determinate.systems/nix/nix-installer-x86_64-linux)
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Nix install plan (v0.0.0-unreleased)

Planner: steam-deck

Planner settings:

* extra_conf: []
* modify_profile: true
* nix_package_url: "https://releases.nixos.org/nix/nix-2.12.0/nix-2.12.0-x86_64-linux.tar.xz"
* channels: ["nixpkgs=https://nixos.org/channels/nixpkgs-unstable"]
* nix_build_group_id: 3000
* nix_build_group_name: "nixbld"
* force: false
* daemon_user_count: 32
* nix_build_user_id_base: 3000
* nix_build_user_prefix: "nixbld"
* persistence: "/home/nix"

The following actions will be taken (`--explain` for more context):

* Create directory `/home/nix`
* Create or overwrite file `/etc/systemd/system/nix-directory.service`
* Create or overwrite file `/etc/systemd/system/nix.mount`
* Create or overwrite file `/etc/systemd/system/ensure-symlinked-units-resolve.service`
* Enable (and start) the systemd unit ensure-symlinked-units-resolve.service
* Fetch `https://releases.nixos.org/nix/nix-2.12.0/nix-2.12.0-x86_64-linux.tar.xz` to `/nix/temp-install-dir`
* Create build users (UID 3000-3032) and group (GID 3000)
* Create a directory tree in `/nix`
* Move the downloaded Nix into `/nix`
* Setup the default Nix profile
* Configure Nix daemon related settings with systemd
* Place the Nix configuration in `/etc/nix/nix.conf`
* Place channel configuration at `/root/.nix-channels`
* Configure the shell profiles
* Enable (and start) the systemd unit nix-daemon.socket


Proceed? (y/N): y
 INFO Step: Create directory `/home/nix`
 INFO Step: Create or overwrite file `/etc/systemd/system/nix-directory.service`
 INFO Step: Create or overwrite file `/etc/systemd/system/nix.mount`
 INFO Step: Create or overwrite file `/etc/systemd/system/ensure-symlinked-units-resolve.service`
 INFO Step: Enable (and start) the systemd unit ensure-symlinked-units-resolve.service
 INFO Step: Provision Nix
 INFO Step: Configure Nix
 INFO Step: Enable (and start) the systemd unit nix-daemon.socket
```

Journal: [journal.txt](https://github.com/DeterminateSystems/nix-installer/files/10314954/journal.txt)

**Comment by Hoverbear** [comment] 2023-01-03 17:02
Thanks for trying it out! I'm sorry it didn't work!

Were you able to uninstall successfully and resolve the issue? Did you need some help recovering the device?

I am looking at the logs, you say the desktop session crashed? I do see the x server crashing, I'm unsure why this would happen since we don't really touch that.

Could you elaborate a bit on how and when it crashed?

In particular I'd like to know:

* Did you run the installer remotely over ssh while the steamos "gamescope" is up? Or via desktop mode?
* How do you mean the desktop session crashed? After running the installer the session errored and closed? Or you only encountered this on restart? Or when trying to turn it off?


Last week after an update to my deck I noticed this issue https://github.com/DeterminateSystems/nix-installer/pull/144, my desktop session went black but did not sleep when I pushed the power button. Unfortunately I did not take a `journalctl` sample before fixing it (it was the holidays and I was off, so I got lazy) so I can't confirm it's your issue.

I'm going to be merging and pushing a new binary to the site today most likely, I'll post a new comment when I have and if you're feeling generous

**Comment by Hoverbear** [comment] 2023-01-03 17:26
I'm unsure if that's your issue as I look at it more. I do see this which seems to be the crux of the issue for you:

```
Dec 28 16:18:38 steamdeck polkitd[1117]: Unregistered Authentication Agent for unix-session:6 (system bus name :1.403, object path /org/kde/PolicyKit1/AuthenticationAgent, locale en_DE.UTF-8) (disconnected from bus)
Dec 28 16:18:38 steamdeck plasmashell[38781]: ICE default IO error handler doing an exit(), pid = 38781, errno = 0
Dec 28 16:18:38 steamdeck kscreen_backend_launcher[37910]: The X11 connection broke (error 1). Did the X11 server die?
Dec 28 16:18:38 steamdeck jupiter-biosupdate[40428]: Performing BIOS updates
Dec 28 16:18:38 steamdeck systemd[1063]: plasma-ksmserver.service: Main process exited, code=exited, status=1/FAILURE
Dec 28 16:18:38 steamdeck systemd[1063]: plasma-ksmserver.service: Failed with result 'exit-code'.
Dec 28 16:18:38 steamdeck systemd[1063]: Stopped KDE Session Management Server.
Dec 28 16:18:38 steamdeck systemd[1063]: Stopped Portal service.
Dec 28 16:18:38 steamdeck systemd[1063]: Stopped Geoclue Demo agent.
Dec 28 16:18:38 steamdeck xdg-desktop-portal-kde[39211]: The X11 connection broke (error 1). Did the X11 server die?
Dec 28 16:18:38 steamdeck systemd[1063]: Stopped Discover.
Dec 28 16:18:38 steamdeck systemd[1063]: app-org.kde.discover.notifier@autostart.service: Consumed 2.333s CPU time.
Dec 28 16:18:38 steamdeck systemd[1063]: Stopped Proxies GTK DBus menus to a Plasma readable format.
Dec 28 16:18:38 steamdeck systemd[1063]: Stopped Handle legacy xembed system tray icons.
Dec 28 16:18:38 steamdeck systemd[1063]: Stopped KActivityManager Activity manager Service.
Dec 28 16:18:38 steamdeck kded5[37733]: The X11 connection broke: I/O error (code 1)
Dec 28 16:18:38 steamdeck kded5[37733]: XIO:  fatal IO error 4 (Interrupted system call) on X server ":0"
Dec 28 16:18:38 steamdeck kded5[37733]:       after 1484 requests (1484 known processed) with 0 events remaining.
```

**Comment by lluchs** [comment] 2023-01-09 15:33
>Were you able to uninstall successfully and resolve the issue? Did you need some help recovering the device?

The installation was successful and everything worked after I restarted the desktop session from the SteamOS UI. So it's really not a huge issue. I also didn't test whether I can reproduce it on my device.

>Did you run the installer remotely over ssh while the steamos "gamescope" is up? Or via desktop mode?

I ran the installer in a terminal in desktop mode.

>How do you mean the desktop session crashed? After running the installer the session errored and closed? Or you only encountered this on restart? Or when trying to turn it off?

Somewhere near the end of the installation the screen went black and the SteamOS UI started again.

My reading of the journal is that the issue happens here and everything else is just reaction to the X server disappearing:

```
Dec 28 16:18:33 steamdeck systemd[1]: Stopping Simple Desktop Display Manager...
Dec 28 16:18:33 steamdeck sddm-helper[37674]: Signal received: SIGTERM
```

But no clue why systemd would stop sddm there.

**Comment by Hoverbear** [comment] 2023-01-09 15:41
We definitely don't send anything SIGTERM... I wonder if it had to do with us creating several users in a very rapid succession?

**Comment by Hoverbear** [comment] 2023-01-09 16:31
I'm going to leave this issue open hoping we find out if others experience it. If so, it's definitely an issue and we can find a fix!

**Comment by Hoverbear** [comment] 2023-01-31 18:02
We've had no new reports of this bug which is relieving. :)

**Comment by Pablo1107** [comment] 2023-02-05 05:25
> We've had no new reports of this bug which is relieving. :)

It happened to me as well. I was able to uninstall it, but everytime I tried the installer again it crash the same as before. Let me know if is something I can provide to help diagnose.

**Comment by Hoverbear** [comment] 2023-02-06 18:06
We also saw #235 which seems to confirm this bug! I have a possible fix in #237.

**Comment by Hoverbear** [comment] 2023-02-10 19:35
We confirmed in #235 that #237 fixed it and there is a listed workaround.

**Comment by Hoverbear** [comment] 2023-02-15 19:38
Should be fixed mainline now. :)

**Closed by Hoverbear** 2023-02-15 19:38 UTC
Labels: bug, Steam Deck, Has workaround
